name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [3.0.2, 2.13.7, 2.12.15, 2.11.12]
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: adopt@1.11
      - uses: coursier/cache-action@v6
      - name: Run Tests
        run: sbt ++${{ matrix.scala }} package doc
